"""empty message

Revision ID: 549b57319801
Revises: 9b32849f358c
Create Date: 2022-08-02 06:37:11.961124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549b57319801'
down_revision = '9b32849f358c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
